#INPUT OF THE SPLIT SCRIPT
#	The binary with the restrcutured dataset generated by restructure.py

#OUTPUT OF THE SPLIT SCRIPT
#	A binary file with the test set
#	A binary file with the training set

#Common path to the whole proyect
main_path = '/home/vic/paper'

#Path to the modules folder. Must be a full path
MODULES_PATH = '{}/modules'.format(main_path)

#Path to the dataset file
datapath =  '{}/data'.format(main_path)
DATASET = '{}/restructured/restructured.pickle'.format(datapath)

#Ratio of windows to teh training set vs the test set
TRAIN_RATE = 0.6

#Size in bytes to filter low traffic volume windows
FILTER_SIZE = 1024 * 3
def WINDOW_FILTER(CW): #Function to be applied
    return ((CW.get_pktSizeSum() > FILTER_SIZE) or (CW.target == 'idle'))

#Store split statistics
STORE_SPLIT_STATISTICS = False
SPLIT_FILE = '{}/results/crossval_split.csv'.format(datapath)

#Output files for the datasets
TRAIN_FILE = '{}/datasets/train.pickle'.format(datapath)
TEST_FILE = '{}/datasets/test.pickle'.format(datapath)

#Enable/disable output
VERBOSE = True
